docs: update docs and add link
linuxdeepin/dtksystemsettings pull request #122
Opened 2022-12-20 03:06 UTC by xzl01

更新文档, 添加链接

Log:

2022-12-20 03:45 UTC, BLumia requested changes

2022-12-20 03:45 UTC, BLumia commented on docs/accounts/index.zh_CN.md
> +[接口文档](group__dtkaccounts.html)
这里的输出仅适用于 html，所以应当配合 `@htmlonly` `@endhtmlonly` 使用。

2022-12-20 03:45 UTC, BLumia commented on docs/accounts/index.zh_CN.md
> +@details [示例文档](md_docs_accounts_index_zh_CN.html)
同上，但如果是对页面的引用而不限于 html，则应当使用 `@ref` 和/或 `@see`

2022-12-20 03:45 UTC, BLumia commented on docs/login/dloginsession.zh_CN.dox
> +@brief 此函数为私有构造函数, 应使用DLoginManager获取该对象, 需要通过调用`DLoginManager::findSessionById()`、`DLoginManager::findSessionByPID()`或者`DLoginManager::currentSession()`函数获取
private 接口应该会被准确识别，且不生成文档。可以看看问题在哪

2022-12-20 03:45 UTC, BLumia commented on docs/login/dloginsession.zh_CN.dox
> +对应Login上的Activate方法, 类似Manger对象的相应调用
还是觉得这种在中文文本中使用英文半角逗号加空格的做法很怪，至今没看到任何其他的文档规范或者实践中有实际使用这种做法。选择这种方式有确切的原因或理由吗？

2022-12-20 03:45 UTC, BLumia commented on docs/rfmanager/index.zh_CN.md
> +[接口文档](group__dtkrfmanager.html)
同上

2022-12-20 03:45 UTC, BLumia commented on docs/systemtime/index.zh_CN.md
> +[接口文档](group__dtksystemtime.html)
同上

2022-12-20 03:45 UTC, BLumia commented on docs/systemtime/index.zh_CN.md
> +@details [示例文档](md_docs_systemtime_index_zh_CN.html)
同上

2022-12-21 02:05 UTC, xzl01 commented on docs/login/dloginsession.zh_CN.dox
> +对应Login上的Activate方法, 类似Manger对象的相应调用
这个原因是在中英文混排的时候会出现标点符号错乱 vscode认为你的中文标点是错误的，标黄。为了舒服和统一使用半角符号+空格的排版。纯粹是因为内部看起来方便

2022-12-21 02:08 UTC, xzl01 commented on docs/login/dloginsession.zh_CN.dox
> +对应Login上的Activate方法, 类似Manger对象的相应调用
如果需要区分中英文符号进行排版，工作量较大，并且这个文档并非出版物，我们较为注重内容，标点符号这个是否被正确使用并不关注。不太想在这个中英文混合排版上花时间

2022-12-21 02:35 UTC, asterwyx approved these changes

2022-12-21 02:42 UTC, Decodetalkers approved these changes

2022-12-21 02:43 UTC, 18202781743 approved these changes

2022-12-21 02:47 UTC, BLumia approved these changes

2022-12-21 02:48 UTC, merged